// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License - see LICENSE file in this repo.
namespace Microsoft.SqlServer.Utils.Misc.SQLCallStackResolver {
    partial class SQLBuildsForm {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing) {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent() {
            this.buildFormStatusStrip = new System.Windows.Forms.StatusStrip();
            this.downloadStatus = new System.Windows.Forms.ToolStripStatusLabel();
            this.downloadProgress = new System.Windows.Forms.ToolStripProgressBar();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.splitContainer2 = new System.Windows.Forms.SplitContainer();
            this.findNext = new System.Windows.Forms.Button();
            this.searchText = new System.Windows.Forms.TextBox();
            this.searchLabel = new System.Windows.Forms.Label();
            this.treeviewSyms = new System.Windows.Forms.TreeView();
            this.checkPDBAvail = new System.Windows.Forms.Button();
            this.dnldButton = new System.Windows.Forms.Button();
            this.buildFormStatusStrip.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer2)).BeginInit();
            this.splitContainer2.Panel1.SuspendLayout();
            this.splitContainer2.Panel2.SuspendLayout();
            this.splitContainer2.SuspendLayout();
            this.SuspendLayout();
            this.buildFormStatusStrip.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.buildFormStatusStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.downloadStatus,
            this.downloadProgress});
            this.buildFormStatusStrip.Location = new System.Drawing.Point(0, 522);
            this.buildFormStatusStrip.Name = "statusStrip1";
            this.buildFormStatusStrip.Padding = new System.Windows.Forms.Padding(1, 0, 10, 0);
            this.buildFormStatusStrip.Size = new System.Drawing.Size(411, 22);
            this.buildFormStatusStrip.TabIndex = 2;
            this.buildFormStatusStrip.Text = "statusStrip1";
            this.downloadStatus.Name = "downloadStatus";
            this.downloadStatus.Size = new System.Drawing.Size(0, 17);
            this.downloadProgress.AccessibleDescription = "Progress of download";
            this.downloadProgress.AccessibleName = "downloadProgress";
            this.downloadProgress.Name = "downloadProgress";
            this.downloadProgress.Size = new System.Drawing.Size(75, 16);
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer1.FixedPanel = System.Windows.Forms.FixedPanel.Panel2;
            this.splitContainer1.IsSplitterFixed = true;
            this.splitContainer1.Location = new System.Drawing.Point(0, 0);
            this.splitContainer1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.splitContainer1.Name = "splitContainer1";
            this.splitContainer1.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.splitContainer1.Panel1.Controls.Add(this.splitContainer2);
            this.splitContainer1.Panel2.Controls.Add(this.checkPDBAvail);
            this.splitContainer1.Panel2.Controls.Add(this.dnldButton);
            this.splitContainer1.Size = new System.Drawing.Size(411, 544);
            this.splitContainer1.SplitterDistance = 475;
            this.splitContainer1.SplitterWidth = 3;
            this.splitContainer1.TabIndex = 3;
            this.splitContainer2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer2.FixedPanel = System.Windows.Forms.FixedPanel.Panel1;
            this.splitContainer2.IsSplitterFixed = true;
            this.splitContainer2.Location = new System.Drawing.Point(0, 0);
            this.splitContainer2.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.splitContainer2.Name = "splitContainer2";
            this.splitContainer2.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.splitContainer2.Panel1.Controls.Add(this.findNext);
            this.splitContainer2.Panel1.Controls.Add(this.searchText);
            this.splitContainer2.Panel1.Controls.Add(this.searchLabel);
            this.splitContainer2.Panel2.Controls.Add(this.treeviewSyms);
            this.splitContainer2.Size = new System.Drawing.Size(411, 475);
            this.splitContainer2.SplitterDistance = 35;
            this.splitContainer2.SplitterWidth = 3;
            this.splitContainer2.TabIndex = 0;
            this.findNext.AccessibleDescription = "Find";
            this.findNext.AccessibleName = "findNext";
            this.findNext.Location = new System.Drawing.Point(351, 7);
            this.findNext.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.findNext.Name = "findNext";
            this.findNext.Size = new System.Drawing.Size(56, 19);
            this.findNext.TabIndex = 2;
            this.findNext.Text = "Find";
            this.findNext.UseVisualStyleBackColor = true;
            this.findNext.Click += new System.EventHandler(this.FindNext_Click);
            this.searchText.AccessibleDescription = "Search term goes here";
            this.searchText.AccessibleName = "searchText";
            this.searchText.Location = new System.Drawing.Point(124, 7);
            this.searchText.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.searchText.Name = "searchText";
            this.searchText.Size = new System.Drawing.Size(223, 20);
            this.searchText.TabIndex = 1;
            this.searchLabel.AutoSize = true;
            this.searchLabel.Location = new System.Drawing.Point(8, 10);
            this.searchLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.searchLabel.Name = "searchLabel";
            this.searchLabel.Size = new System.Drawing.Size(116, 13);
            this.searchLabel.TabIndex = 0;
            this.searchLabel.Text = "SQL version / keyword";
            this.treeviewSyms.AccessibleDescription = "SQL Server versions and builds";
            this.treeviewSyms.AccessibleName = "treeviewSyms";
            this.treeviewSyms.Dock = System.Windows.Forms.DockStyle.Fill;
            this.treeviewSyms.Location = new System.Drawing.Point(0, 0);
            this.treeviewSyms.Name = "treeviewSyms";
            this.treeviewSyms.Size = new System.Drawing.Size(411, 437);
            this.treeviewSyms.TabIndex = 1;
            this.checkPDBAvail.AccessibleDescription = "Check if public PDBs for this build are available";
            this.checkPDBAvail.AccessibleName = "checkPDBAvail";
            this.checkPDBAvail.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.checkPDBAvail.Location = new System.Drawing.Point(66, 12);
            this.checkPDBAvail.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.checkPDBAvail.Name = "checkPDBAvail";
            this.checkPDBAvail.Size = new System.Drawing.Size(128, 26);
            this.checkPDBAvail.TabIndex = 3;
            this.checkPDBAvail.Text = "Check PDB availability";
            this.checkPDBAvail.UseVisualStyleBackColor = true;
            this.checkPDBAvail.Click += new System.EventHandler(this.CheckPDBAvail_Click);
            this.dnldButton.AccessibleDescription = "Download public PDBs";
            this.dnldButton.AccessibleName = "dnldButton";
            this.dnldButton.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.dnldButton.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.dnldButton.Location = new System.Drawing.Point(199, 12);
            this.dnldButton.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.dnldButton.Name = "dnldButton";
            this.dnldButton.Size = new System.Drawing.Size(142, 26);
            this.dnldButton.TabIndex = 2;
            this.dnldButton.Text = "Download PDBs";
            this.dnldButton.UseVisualStyleBackColor = true;
            this.dnldButton.Click += new System.EventHandler(this.DownloadPDBs);
            this.AcceptButton = this.dnldButton;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(411, 544);
            this.Controls.Add(this.buildFormStatusStrip);
            this.Controls.Add(this.splitContainer1);
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "SQLBuildsForm";
            this.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Hide;
            this.Text = "Select SQL build";
            this.Load += new System.EventHandler(this.Treeview_Load);
            this.buildFormStatusStrip.ResumeLayout(false);
            this.buildFormStatusStrip.PerformLayout();
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            this.splitContainer2.Panel1.ResumeLayout(false);
            this.splitContainer2.Panel1.PerformLayout();
            this.splitContainer2.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer2)).EndInit();
            this.splitContainer2.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }
        #endregion
        private System.Windows.Forms.StatusStrip buildFormStatusStrip;
        private System.Windows.Forms.ToolStripStatusLabel downloadStatus;
        private System.Windows.Forms.ToolStripProgressBar downloadProgress;
        private System.Windows.Forms.SplitContainer splitContainer1;
        private System.Windows.Forms.Button dnldButton;
        private System.Windows.Forms.Button checkPDBAvail;
        private System.Windows.Forms.SplitContainer splitContainer2;
        private System.Windows.Forms.TreeView treeviewSyms;
        private System.Windows.Forms.TextBox searchText;
        private System.Windows.Forms.Label searchLabel;
        private System.Windows.Forms.Button findNext;
    }
}
