name: Build SQLCallStackResolver
on:
  pull_request:
  workflow_dispatch:
    inputs:
      testsfilter:
        description: 'Filter expression to use for running tests'
        default: 'TestCategory=Unit|TestCategory=Perf'
        required: false
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
    - name: Setup NuGet
      uses: NuGet/setup-nuget@b26b823c478ee115be5c9403e62c90b0bf943843 # v3.1.0
    - name: Restore NuGet Packages
      run: nuget restore SQLCallStackResolver.sln
    - name: Build SQLCallStackResolver
      run: msbuild SQLCallStackResolver.sln /p:Configuration=Release
    - name: Upload Artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: SQLCallStackResolver
        path: |
          Target/Release
          !Target/Release/*.xml
          !Target/Release/Tests
    - name: Prep for running tests
      run: ./downloadsyms.ps1
      working-directory: Tests/TestCases
      shell: powershell
    - name: Run tests
      run: |
        ../../../utils/import-vsenv.ps1
        & "$env:VSINSTALLDIR/Common7/IDE/Extensions/TestPlatform/vstest.console.exe" ./SQLCalLStackResolver.Tests.dll /Parallel /logger:"console;verbosity=normal" /TestCaseFilter:"${{ github.event.inputs.testsfilter || 'TestCategory=Unit' }}"
      working-directory: Target/Release/Tests
      shell: powershell
